// <copyright file="NeuronClassTest.Constructor01.g.cs" company="Monash University">Copyright © Monash University 2009</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace SpikingLibrary
{
    public partial class NeuronClassTest
    {
[TestMethod]
[PexGeneratedBy(typeof(NeuronClassTest))]
public void Constructor01610()
{
    NeuronClass neuronClass;
    neuronClass = this.Constructor01(0, 1, 0, 0, 12.5);
    Assert.IsNotNull((object)neuronClass);
    Assert.AreEqual<string>((string)null, neuronClass.Label);
}
[TestMethod]
[PexGeneratedBy(typeof(NeuronClassTest))]
public void Constructor01837()
{
    NeuronClass neuronClass;
    neuronClass = this.Constructor01(-1, 0, 0, 0, 0);
    Assert.IsNotNull((object)neuronClass);
    Assert.AreEqual<string>((string)null, neuronClass.Label);
}
[TestMethod]
[PexGeneratedBy(typeof(NeuronClassTest))]
public void Constructor01446()
{
    NeuronClass neuronClass;
    neuronClass = this.Constructor01(0, 0, 0, 0, 0);
    Assert.IsNotNull((object)neuronClass);
    Assert.AreEqual<string>((string)null, neuronClass.Label);
}
[TestMethod]
[PexGeneratedBy(typeof(NeuronClassTest))]
public void Constructor473()
{
    NeuronClass neuronClass;
    neuronClass = this.Constructor();
    Assert.IsNotNull((object)neuronClass);
    Assert.AreEqual<string>("Phasic Spiking", neuronClass.Label);
}
    }
}
