// <copyright file="NonLearningSynapseFactoryTest.CreateSynapse.g.cs" company="Monash University">Copyright © Monash University 2009</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using MathLib.Statistics;
using Microsoft.Pex.Framework.Explorable;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace SpikingLibrary
{
    public partial class NonLearningSynapseFactoryTest
    {
[TestMethod]
[PexGeneratedBy(typeof(NonLearningSynapseFactoryTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void CreateSynapseThrowsContractException84()
{
    try
    {
      if (!PexContract.HasRequiredRuntimeContracts
               (typeof(NonLearningSynapseFactory), (PexRuntimeContractsFlags)28799))
        Assert.Inconclusive
            ("assembly SpikingLibrary is not instrumented with runtime contracts");
      ConstantGenerator constantGenerator;
      NonLearningSynapseFactory nonLearningSynapseFactory;
      Synapse synapse;
      constantGenerator = new ConstantGenerator(0);
      nonLearningSynapseFactory =
        PexInvariant.CreateInstance<NonLearningSynapseFactory>();
      PexInvariant.SetField<INumberGenerator>((object)nonLearningSynapseFactory, 
                                              "_delayGenerator", (INumberGenerator)constantGenerator);
      PexInvariant.SetField<INumberGenerator>((object)nonLearningSynapseFactory, 
                                              "_weightGenerator", (INumberGenerator)constantGenerator);
      PexInvariant.CheckInvariant((object)nonLearningSynapseFactory);
      synapse = this.CreateSynapse(nonLearningSynapseFactory, (Neuron)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(NonLearningSynapseFactoryTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void CreateSynapseThrowsContractException788()
{
    try
    {
      if (!PexContract.HasRequiredRuntimeContracts
               (typeof(NonLearningSynapseFactory), (PexRuntimeContractsFlags)28799))
        Assert.Inconclusive
            ("assembly SpikingLibrary is not instrumented with runtime contracts");
      NormalRandomGenerator normalRandomGenerator;
      NonLearningSynapseFactory nonLearningSynapseFactory;
      Synapse synapse;
      normalRandomGenerator = new NormalRandomGenerator(0, 0, 0);
      nonLearningSynapseFactory =
        PexInvariant.CreateInstance<NonLearningSynapseFactory>();
      PexInvariant.SetField<INumberGenerator>((object)nonLearningSynapseFactory, 
                                              "_delayGenerator", (INumberGenerator)normalRandomGenerator);
      PexInvariant.SetField<INumberGenerator>((object)nonLearningSynapseFactory, 
                                              "_weightGenerator", (INumberGenerator)normalRandomGenerator);
      PexInvariant.CheckInvariant((object)nonLearningSynapseFactory);
      synapse = this.CreateSynapse(nonLearningSynapseFactory, (Neuron)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(NonLearningSynapseFactoryTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void CreateSynapseThrowsContractException630()
{
    try
    {
      if (!PexContract.HasRequiredRuntimeContracts
               (typeof(NonLearningSynapseFactory), (PexRuntimeContractsFlags)28799))
        Assert.Inconclusive
            ("assembly SpikingLibrary is not instrumented with runtime contracts");
      UniformRandomGenerator uniformRandomGenerator;
      NonLearningSynapseFactory nonLearningSynapseFactory;
      Synapse synapse;
      uniformRandomGenerator = new UniformRandomGenerator(0, 0);
      nonLearningSynapseFactory =
        PexInvariant.CreateInstance<NonLearningSynapseFactory>();
      PexInvariant.SetField<INumberGenerator>((object)nonLearningSynapseFactory, 
                                              "_delayGenerator", (INumberGenerator)uniformRandomGenerator);
      PexInvariant.SetField<INumberGenerator>((object)nonLearningSynapseFactory, 
                                              "_weightGenerator", (INumberGenerator)uniformRandomGenerator);
      PexInvariant.CheckInvariant((object)nonLearningSynapseFactory);
      synapse = this.CreateSynapse(nonLearningSynapseFactory, (Neuron)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
